[package]
name = "kde_color"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
palette = "0.7.2"
toml_edit = "0.19.14"
